const strings = {
  MENU_PUT_EXTRA_KEY: 'MENU_PUT_EXTRA_KEY',
  LOADED_INTRO: 'LOADED_INTRO',
  TOKEN: 'TOKEN',
  REQUEST_PUT_EXTRA_KEY: 'REQUEST_PUT_EXTRA_KEY',
  URL_PUT_EXTRA_KEY: 'URL_PUT_EXTRA_KEY',
  HEADER_PUT_EXTRA_KEY: 'HEADER_PUT_EXTRA_KEY',
  LST_MENU_PUT_EXTRA: 'LST_MENU_PUT_EXTRA',
  LST_CATEGORY_PUT_EXTRA: 'LST_CATEGORY_PUT_EXTRA',
};
export default strings;
